# Generated by Django 5.2.5 on 2025-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
