# Generated by Django 5.2.5 on 2025-10-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_city_alter_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
        migrations.AddField(
            model_name='user',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='user_document_back/'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='user_document_front/'),
        ),
    ]
