# Generated by Django 5.2.5 on 2025-11-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_document_user_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
