# Generated by Django 5.2.5 on 2026-01-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supporttype',
            name='name',
        ),
        migrations.AddField(
            model_name='supporttype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporttype',
            name='description_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supporttype',
            name='name_hr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
