# Generated by Django 5.2.5 on 2025-12-25 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0003_payment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoversAllSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='covers_all_subscription', to='paymentApp.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers_all_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
