# Generated by Django 5.2.5 on 2025-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
