# Generated by Django 5.2.5 on 2026-01-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0006_charges_base_amount'),
        ('listing', '0002_alter_service_description_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='adminHandlers.servicecategory'),
        ),
        migrations.AlterField(
            model_name='listingfeatures',
            name='feature_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminHandlers.categoryfeaturesfield'),
        ),
    ]
