# Generated by Django 5.2.5 on 2025-09-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('charge_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('for_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('for_label', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
