# Generated by Django 5.2.5 on 2025-09-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0002_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryfeaturesfield',
            old_name='label',
            new_name='label_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='question_en',
        ),
        migrations.RenameField(
            model_name='propertycategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='categoryfeaturesfield',
            name='label_hr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='name_hr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_hr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
