# Generated by Django 5.2.5 on 2025-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0003_rename_label_categoryfeaturesfield_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfeaturesfield',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
