# Generated by Django 5.2.5 on 2025-10-05 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0004_categoryfeaturesfield_unit'),
        ('listing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyCategory',
            new_name='ServiceCategory',
        ),
    ]
