# Generated by Django 5.2.5 on 2025-11-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHandlers', '0005_rename_propertycategory_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
