# Generated by Django 5.2.5 on 2025-11-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.JSONField()),
                ('recipients', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('trigger_type', models.CharField(choices=[('immediately', 'Immediately'), ('recurring', 'Recurring'), ('custom', 'Custom')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('interval_days', 'Every X Days'), ('interval_hours', 'Every X Hours')], max_length=20, null=True)),
                ('recurring_interval', models.PositiveIntegerField(blank=True, help_text='Used when frequency is interval_days or interval_hours', null=True)),
                ('recurring_start', models.DateTimeField(blank=True, null=True)),
                ('recurring_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
