# Generated by Django 5.2.5 on 2025-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
