# Generated by Django 5.2.5 on 2025-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0004_notification_data_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(default='in_app', max_length=20),
        ),
    ]
